### ISSUE TITLE
Evaluate NLP results with reasons

### ISSUE THREAD

**Issue by abdullahgulraiz** [abdullahgulraiz/SeFiLa#18]
Allow user to upload a report generated from SeFiDeF and assign reasoning (both NLP and DevSecOps) to each finding so we can explain in the broader perspective how deduplication performed and where it is limited.

**Comment by abdullahgulraiz** [comment]
### Todos

- [x] Scaffold component and implement basics
- [x] Reasons
  - [x] Add
  - [x] Edit
  - [x] Delete
- [x] Associate Reasons with predictions
- [x] Reasons should load automatically (currently load on closing of modal)
- [ ] Scrollable div for List of Reasons
- [ ] Highlight similar words in predictions texts
- [x] Download evaluation
- [x] Reasons API
